### PR TITLE
feat: support vote and some query

### PR DESCRIPTION
**Pull request by JoowonYun**
Content
--
- refactoring query
- delegate query(cli, rest)
- vote
- about integration code

Example
--
- delegate query cli
```
$ clif hdac delegator [<vaidator-address>] [--from <from>]

// The delegate info of a specific validator
$ clif hdac delegator 'fridayxxxxxxxxxxxxx'

// Quantity of each stake in a specific delegator
$ clif hdac delegator --from 'fridayxxxxxxxxxxxxx'

// Both (self delegate or The delegate quantity of a specific validator)
$ clif hdac delegator 'fridayxxxxxxxxxxxxx' --from 'fridayxxxxxxxxxxxxx'
```
- delegate query rest
```
// The delegate info of a specific validator
$ http://localhost:1317/hdac/delegator?delegator=fridayxxxxxxxxxxxxx

// Quantity of each stake in a specific delegator
$ http://localhost:1317/hdac/delegator?validator=fridayxxxxxxxxxxxxx

// Both (self delegate or The delegate quantity of a specific validator)
$ http://localhost:1317/hdac/delegator?delegator=fridayxxxxxxxxxxxxx&validator=fridayxxxxxxxxxxxxx
```
- vote cli
```
$ clif hdac vote <hash> <amount> <fee> <gas-price> --from <from>

$ clif hdac vote 0000000000000000000000000000000000000000000000000000000000000000 1 0.00
2 30000000 --from fridayxxxxxxxxxxxxx
```
- unvote cli
```
$ clif hdac unvote <hash> <amount> <fee> <gas-price> --from <from>

$ clif hdac unvote 0000000000000000000000000000000000000000000000000000000000000000 1 0.00
2 30000000 --from fridayxxxxxxxxxxxxx
```
- vote query cli
```
$ clif hdac voter [<hash>] [--from <from>]

// The vote info of a specific dapp
$ clif hdac voter 0000000000000000000000000000000000000000000000000000000000000000

// Quantity of each vote in a specific voter
$ clif hdac voter --from fridayxxxxxxxxxxxxx

// Both
$ clif hdac voter 0000000000000000000000000000000000000000000000000000000000000000 --from fridayxxxxxxxxxxxxx
```
- vote query rest
```
// The vote info of a specific dapp
$ localhost:1317/hdac/voter?hash=0000000000000000000000000000000000000000000000000000000000000000

// Quantity of each vote in a specific voter
$ localhost:1317/hdac/voter?address=fridayxxxxxxxxxxxxx

// Both
$ localhost:1317/hdac/voter?address=fridayxxxxxxxxxxxxx&hash=0000000000000000000000000000000000000000000000000000000000000000
```

Issue
--
When creating an account or creating a contract in execution-engine, it becomes 32 bytes without prefix. In order to use this externally, discussion of the address structure is necessary. https://github.com/hdac-io/friday/issues/98

### CODE REVIEW

**Comment by psy2848048** [comment]
Bond/Unbond/Redelegation/Undelegation fails due to gas limit in integration test

**Comment by JoowonYun** [comment]
> Bond/Unbond/Redelegation/Undelegation fails due to gas limit in integration test
> 
> ```json
>   "raw_log": "[{\"msg_index\":0,\"success\":true,\"log\":\"%!(EXTRA string=ERROR:\\nCodespace: contract\\nCode: 302\\nMessage: \\\"execution engine - deploy error - execute : %!(EXTRA string=Interpreter(Trap(Trap { kind: Host(GasLimit) })))\\\"\\n)\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"executionengine\"}]}]}]",
>   "logs": [
>     {
>       "msg_index": 0,
>       "success": true,
>       "log": "%!(EXTRA string=ERROR:\nCodespace: contract\nCode: 302\nMessage: \"execution engine - deploy error - execute : %!(EXTRA string=Interpreter(Trap(Trap { kind: Host(GasLimit) })))\"\n)",
> ```

Where..? It seems to be no problem on travis.

**Comment by psy2848048** [comment]
> > Bond/Unbond/Redelegation/Undelegation fails due to gas limit in integration test
> > ```json
> >   "raw_log": "[{\"msg_index\":0,\"success\":true,\"log\":\"%!(EXTRA string=ERROR:\\nCodespace: contract\\nCode: 302\\nMessage: \\\"execution engine - deploy error - execute : %!(EXTRA string=Interpreter(Trap(Trap { kind: Host(GasLimit) })))\\\"\\n)\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"executionengine\"}]}]}]",
> >   "logs": [
> >     {
> >       "msg_index": 0,
> >       "success": true,
> >       "log": "%!(EXTRA string=ERROR:\nCodespace: contract\nCode: 302\nMessage: \"execution engine - deploy error - execute : %!(EXTRA string=Interpreter(Trap(Trap { kind: Host(GasLimit) })))\"\n)",
> > ```
> 
> Where..? It seems to be no problem on travis.

Because tx query appears `"success": true` even though it fails..
Tx checker checks `"success": true`. Do I need to change the logic?

**Comment by JoowonYun** [comment]
> > > Bond/Unbond/Redelegation/Undelegation fails due to gas limit in integration test
> > > ```json
> > >   "raw_log": "[{\"msg_index\":0,\"success\":true,\"log\":\"%!(EXTRA string=ERROR:\\nCodespace: contract\\nCode: 302\\nMessage: \\\"execution engine - deploy error - execute : %!(EXTRA string=Interpreter(Trap(Trap { kind: Host(GasLimit) })))\\\"\\n)\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"executionengine\"}]}]}]",
> > >   "logs": [
> > >     {
> > >       "msg_index": 0,
> > >       "success": true,
> > >       "log": "%!(EXTRA string=ERROR:\nCodespace: contract\nCode: 302\nMessage: \"execution engine - deploy error - execute : %!(EXTRA string=Interpreter(Trap(Trap { kind: Host(GasLimit) })))\"\n)",
> > > ```
> > 
> > 
> > Where..? It seems to be no problem on travis.
> 
> Because tx query appears `"success": true` even though it fails..
> Tx checker checks `"success": true`. Do I need to change the logic?

I add to check delegate amount.
So, If have a deploy error, the integration test cannot be successful. I will check again.

**Comment by psy2848048** [comment]
> > > > Bond/Unbond/Redelegation/Undelegation fails due to gas limit in integration test
> > > > ```json
> > > >   "raw_log": "[{\"msg_index\":0,\"success\":true,\"log\":\"%!(EXTRA string=ERROR:\\nCodespace: contract\\nCode: 302\\nMessage: \\\"execution engine - deploy error - execute : %!(EXTRA string=Interpreter(Trap(Trap { kind: Host(GasLimit) })))\\\"\\n)\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"executionengine\"}]}]}]",
> > > >   "logs": [
> > > >     {
> > > >       "msg_index": 0,
> > > >       "success": true,
> > > >       "log": "%!(EXTRA string=ERROR:\nCodespace: contract\nCode: 302\nMessage: \"execution engine - deploy error - execute : %!(EXTRA string=Interpreter(Trap(Trap { kind: Host(GasLimit) })))\"\n)",
> > > > ```
> > > 
> > > 
> > > Where..? It seems to be no problem on travis.
> > 
> > 
> > Because tx query appears `"success": true` even though it fails..
> > Tx checker checks `"success": true`. Do I need to change the logic?
> 
> I add to check delegate amount.
> So, If have a deploy error, the integration test cannot be successful. I will check again.

Sure. You may find the log in travis build.

**Comment by yoosah** [comment]
`--from <wallet alias>` doesn't work when query delegator and voter.

**Comment by yoosah** [comment]
qxw

**Comment by JoowonYun** [comment]
rebase

**Pull request merged**
