### PR TITLE
Introduce special address "system"

### PR DESCRIPTION
**Pull request by caramis**

### CODE REVIEW

**Comment by caramis** [comment]
We can use "system" as a address alias of EE system account.

**Comment by psy2848048** [comment]
In my local:

```
--- FAIL: TestQueryKeyToBytes (0.01s)
    keeper_test.go:31: 
                Error Trace:    keeper_test.go:31
                Error:          Expected value not to be nil.
                Test:           TestQueryKeyToBytes
--- FAIL: TestCreateBlock (0.12s)
panic: client_api_proxy must exist. Check systemcontract. [recovered]
        panic: client_api_proxy must exist. Check systemcontract.

goroutine 39 [running]:
testing.tRunner.func1(0xc0003e2100)
        /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:874 +0x3a3
panic(0x4ac1220, 0xc000078380)
        /usr/local/Cellar/go/1.13/libexec/src/runtime/panic.go:679 +0x1b2
github.com/hdac-io/friday/x/executionlayer.genesis(0xc00012e310, 0x4f91fa0, 0xc0000be008, 0x4f9e3e0, 0xc0001d4200, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/bryan/gerrit/friday/x/executionlayer/test_common.go:134 +0x7fd
github.com/hdac-io/friday/x/executionlayer.TestCreateBlock(0xc0003e2100)
        /Users/bryan/gerrit/friday/x/executionlayer/keeper_test.go:91 +0x8e
testing.tRunner(0xc0003e2100, 0x4e4f910)
        /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
        /usr/local/Cellar/go/1.13/libexec/src/testing/testing.go:960 +0x350
exit status 2
FAIL    github.com/hdac-io/friday/x/executionlayer      0.457s
```

**Comment by jhyeom26** [comment]
It would be great if you leave this in the documentation. :+1:

**Comment by caramis** [comment]
example usage
> clif contract query address system mint

**Pull request merged**
