### PR TITLE
attach friday consensus

### PR DESCRIPTION
**Pull request by slave5vw**
will squash again for the merged commit(consensus pr # 17 and # 18).

### CODE REVIEW

**Comment by slave5vw** [comment]
If integration_test is run locally, all passes.
However, in ci, the transaction was executed normally, but since there is no response, the timeout has failed.
After checked, I will request the review again.

**Comment by JoowonYun** [comment]
When creating a local testnet, the following error occurs.
```
I[2020-05-07|13:12:08.042] starting ABCI with Tendermint                module=main 
Error reading PrivValidator state from /Users/yun/.nodef/data/priv_validator_state.json: JSON encoding of interfaces require non-empty type field.

**Comment by slave5vw** [comment]
redirected commit hash in go.mod  to some pr merged tendermint branch.
please review again!

**Comment by slave5vw** [comment]
In Mac ci, the problem that the EE socket was not connected and failed to restart was solved by adding a process kill wait time. @psy2848048 Thanks!

**Comment by slave5vw** [comment]
rebased to latest master and changed commit hash by merged tendermint.

**Pull request merged**
